knx_master = [
    {
        "device_type_id": 1,
        "sub_device_type_id": 1,
        "address_name_technical": "on_off",
        "address_name": "On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 1,
        "address_name_technical": "on_off_status",
        "address_name": "On/Off Status",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 3,
        "address_name_technical": "on_off",
        "address_name": "On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 3,
        "address_name_technical": "on_off_status",
        "address_name": "On/Off Status",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 3,
        "address_name_technical": "dimming_level",
        "address_name": "Dimming Level",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 3,
        "address_name_technical": "dimming_status",
        "address_name": "Dimming Status",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    ## RGB color
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "on_off",
        "address_name": "On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "on_off_status",
        "address_name": "On/Off Status",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "dimmimg_level",
        "address_name": "Dimming Level",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "dimming_status",
        "address_name": "Dimming Status",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "rgb_color",
        "address_name": "RGB Color",
        "value_data_type": "RGB",
        "vale_data_range": "(0-255,0-255,0-255)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "r_on_off",
        "address_name": "R On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "r_dimming",
        "address_name": "R Dimming",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "r_status",
        "address_name": "R Status",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "g_on_off",
        "address_name": "G On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "g_dimming",
        "address_name": "G Dimming",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "g_status",
        "address_name": "G Status",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "b_on_off",
        "address_name": "B On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "b_dimming",
        "address_name": "B Dimming",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 2,
        "address_name_technical": "b_status",
        "address_name": "B Status",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    ## CCT
    {
        "device_type_id": 1,
        "sub_device_type_id": 4,
        "address_name_technical": "on_off",
        "address_name": "On/Off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 4,
        "address_name_technical": "on_off_status",
        "address_name": "On/Off Status",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 4,
        "address_name_technical": "dimming_level",
        "address_name": "Dimming Level",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 4,
        "address_name_technical": "dimming_status",
        "address_name": "Dimming Status",
        "value_data_type": "Unsigned Int",
        "vale_data_range": "0 to 255 (Dimming Level)",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 4,
        "address_name_technical": "color_temprature",
        "address_name": "Color Temperature",
        "value_data_type": "2 byte",
        "vale_data_range": "1000k to 10000k",
    },
    {
        "device_type_id": 1,
        "sub_device_type_id": 4,
        "address_name_technical": "color_temprature_status",
        "address_name": "Color Temperature Status",
        "value_data_type": "2 byte",
        "vale_data_range": "1000k to 10000k",
    },
    ## AC- HVAC
    {
        "device_type_id": 2,
        "sub_device_type_id": 5,
        "address_name_technical": "basic_setpoint",
        "address_name": "Basic Setpoint",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 5,
        "address_name_technical": "setpoint_status",
        "address_name": "Setpoint Status",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 5,
        "address_name_technical": "mode",
        "address_name": "Mode",
        "value_data_type": "1 byte",
        "vale_data_range": "Cool,Heat",
    },
    ## AC Split
    {
        "device_type_id": 2,
        "sub_device_type_id": 6,
        "address_name_technical": "basic_setpoint",
        "address_name": "Basic Setpoint",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 6,
        "address_name_technical": "setpoint_status",
        "address_name": "Setpoint Status",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 6,
        "address_name_technical": "mode",
        "address_name": "Mode",
        "value_data_type": "1 byte",
        "vale_data_range": "Cool,Heat",
    },
    ## AHU Split
    {
        "device_type_id": 2,
        "sub_device_type_id": 7,
        "address_name_technical": "basic_setpoint",
        "address_name": "Basic Setpoint",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 7,
        "address_name_technical": "setpoint_status",
        "address_name": "Setpoint Status",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 7,
        "address_name_technical": "mode",
        "address_name": "Mode",
        "value_data_type": "1 byte",
        "vale_data_range": "Cool,Heat",
    },
    # ## AHU Split
    # {
    #     "device_type_id": 2,
    #     "sub_device_type_id": 8,
    #     "address_name_technical": "",
    #     "address_name": "Basic Setpoint",
    #     "value_data_type": "2 byte",
    #     "vale_data_range": "10-40 Degree Celcius",
    # },
    # {
    #     "device_type_id": 2,
    #     "sub_device_type_id": 8,
    #     "address_name_technical": "",
    #     "address_name": "Setpoint Status",
    #     "value_data_type": "2 byte",
    #     "vale_data_range": "10-40 Degree Celcius",
    # },
    # {
    #     "device_type_id": 2,
    #     "sub_device_type_id": 8,
    #     "address_name_technical": "",
    #     "address_name": "Mode",
    #     "value_data_type": "1 byte",
    #     "vale_data_range": "Cool,Heat",
    # },
    ## FCU Split
    {
        "device_type_id": 2,
        "sub_device_type_id": 8,
        "address_name_technical": "basic_setpoint",
        "address_name": "Basic Setpoint",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 8,
        "address_name_technical": "setpoint_status",
        "address_name": "Setpoint Status",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 8,
        "address_name_technical": "mode",
        "address_name": "Mode",
        "value_data_type": "1 byte",
        "vale_data_range": "Cool,Heat",
    },
    ## VRV Split
    {
        "device_type_id": 2,
        "sub_device_type_id": 9,
        "address_name_technical": "basic_setpoint",
        "address_name": "Basic Setpoint",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 9,
        "address_name_technical": "setpoint_status",
        "address_name": "Setpoint Status",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 9,
        "address_name_technical": "mode",
        "address_name": "Mode",
        "value_data_type": "1 byte",
        "vale_data_range": "Cool,Heat",
    },
    ## VFV Split
    {
        "device_type_id": 2,
        "sub_device_type_id": 10,
        "address_name_technical": "basic_setpoint",
        "address_name": "Basic Setpoint",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 10,
        "address_name_technical": "setpoint_status",
        "address_name": "Setpoint Status",
        "value_data_type": "2 byte",
        "vale_data_range": "10-40 Degree Celcius",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 10,
        "address_name_technical": "mode",
        "address_name": "Mode",
        "value_data_type": "1 byte",
        "vale_data_range": "Cool,Heat",
    },
    ## Curtain Horizonatal
    {
        "device_type_id": 3,
        "sub_device_type_id": 11,
        "address_name_technical": "shutter_move",
        "address_name": "Shutter Move",
        "value_data_type": "1 byte",
        "vale_data_range": "0 = Up,1 = Down",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 11,
        "address_name_technical": "shutter_stop",
        "address_name": "Shutter Stop",
        "value_data_type": "1 byte",
        "vale_data_range": "0/1 = stop",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 11,
        "address_name_technical": "shutter_direct_position",
        "address_name": "Shutter Direct Position",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 11,
        "address_name_technical": "shutter_position_status",
        "address_name": "Shutter Position status",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    ## Curtain Vertical
    {
        "device_type_id": 3,
        "sub_device_type_id": 12,
        "address_name_technical": "shutter_move",
        "address_name": "Shutter Move",
        "value_data_type": "1 byte",
        "vale_data_range": "0 = Up,1 = Down",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 12,
        "address_name_technical": "shutter_stop",
        "address_name": "Shutter Stop",
        "value_data_type": "1 byte",
        "vale_data_range": "0/1 = stop",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 12,
        "address_name_technical": "shutter_direct_position",
        "address_name": "Shutter Direct Position",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 12,
        "address_name_technical": "shutter_direct_status",
        "address_name": "Shutter Position status",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    ## Curtains Blinds
    {
        "device_type_id": 3,
        "sub_device_type_id": 13,
        "address_name_technical": "shutter_move",
        "address_name": "Shutter Move",
        "value_data_type": "1 byte",
        "vale_data_range": "0 = Up,1 = Down",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 13,
        "address_name_technical": "shutter_stop",
        "address_name": "Shutter Stop",
        "value_data_type": "1 byte",
        "vale_data_range": "0/1 = stop",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 13,
        "address_name_technical": "shutter_direct_position",
        "address_name": "Shutter Direct Position",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 13,
        "address_name_technical": "shutter_position_status",
        "address_name": "Shutter Position status",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    ## Fan AC
    {
        "device_type_id": 3,
        "sub_device_type_id": 14,
        "address_name_technical": "fan_on_off",
        "address_name": "Fan on/off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 14,
        "address_name_technical": "fan_speed",
        "address_name": "Fan speed",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 14,
        "address_name_technical": "fan_status",
        "address_name": "Fan Status",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    ## Fan DC
    {
        "device_type_id": 3,
        "sub_device_type_id": 15,
        "address_name_technical": "fan_on_off",
        "address_name": "Fan on/off",
        "value_data_type": "On/Off",
        "vale_data_range": "0 or 1",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 15,
        "address_name_technical": "fan_speed",
        "address_name": "Fan speed",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
    {
        "device_type_id": 3,
        "sub_device_type_id": 15,
        "address_name_technical": "fan_status",
        "address_name": "Fan Status",
        "value_data_type": "1 byte",
        "vale_data_range": "0-100%",
    },
]
