bacnet_master = [
    # HVAC
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "hvac",
        "technica_name": "get_temp_status",
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "hvac",
        "technica_name": "set_temp_thermostat",
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "hvac",
        "technica_name": "set_temp_ac",
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # AHU
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "ahu",
        "technica_name": "get_temp_status",
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "ahu",
        "technica_name": "set_temp_thermostat",
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "ahu",
        "technica_name": "set_temp_ac",
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # split ac
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "split_ac",
        "technica_name": "get_temp_status",
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "split_ac",
        "technica_name": "set_temp_thermostat",
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "split_ac",
        "technica_name": "set_temp_ac",
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # FCU
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "fcu",
        "technica_name": "get_temp_status",
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "fcu",
        "technica_name": "set_temp_thermostat",
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "fcu",
        "technica_name": "set_temp_ac",
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # VRV
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrv",
        "technica_name": "get_temp_status",
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrv",
        "technica_name": "set_temp_thermostat",
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrv",
        "technica_name": "set_temp_ac",
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # VFV
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrf",
        "technica_name": "get_temp_status",
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrf",
        "technica_name": "set_temp_thermostat",
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrf",
        "technica_name": "set_temp_ac",
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
]
