bacnet_master = [
    # HVAC
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "hvac",
        "technica_name": "set_point",
        "function": "Set Point",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "hvac",
        "technica_name": "fan",
        "function": "Fan",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "hvac",
        "technica_name": "room_internal_temp",
        "function": "Room Internal Temp",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Read",
    },
    # AHU
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "ahu",
        "technica_name": "set_point",
        "function": "Set Point",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "ahu",
        "technica_name": "fan",
        "function": "Fan",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "ahu",
        "technica_name": "room_internal_temp",
        "function": "Room Internal Temp",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Read",
    },
    # split_ac
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "split_ac",
        "technica_name": "set_point",
        "function": "Set Point",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "split_ac",
        "technica_name": "fan",
        "function": "Fan",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "split_ac",
        "technica_name": "room_internal_temp",
        "function": "Room Internal Temp",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Read",
    },
    # FCU
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "fcu",
        "technica_name": "set_point",
        "function": "Set Point",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "fcu",
        "technica_name": "fan",
        "function": "Fan",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "fcu",
        "technica_name": "room_internal_temp",
        "function": "Room Internal Temp",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Read",
    },
    # VRV
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrv",
        "technica_name": "set_point",
        "function": "Set Point",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrv",
        "technica_name": "fan",
        "function": "Fan",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrv",
        "technica_name": "room_internal_temp",
        "function": "Room Internal Temp",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Read",
    },
    # VRF
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrf",
        "technica_name": "set_point",
        "function": "Set Point",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrf",
        "technica_name": "fan",
        "function": "Fan",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Write",
    },
    {
        "device_type_id": "air_conditioner",
        "sub_device_type_id": "vrf",
        "technica_name": "room_internal_temp",
        "function": "Room Internal Temp",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Read",
    },
]
