bacnet_master = [
    # HVAC
    {
        "device_type_id": 2,
        "sub_device_type_id": 6,
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 6,
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 6,
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # AHU
    {
        "device_type_id": 2,
        "sub_device_type_id": 7,
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 7,
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 7,
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # AHU
    {
        "device_type_id": 2,
        "sub_device_type_id": 8,
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 8,
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 8,
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # FCU
    {
        "device_type_id": 2,
        "sub_device_type_id": 9,
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 9,
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 9,
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # VRV
    {
        "device_type_id": 2,
        "sub_device_type_id": 10,
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 10,
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 10,
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
    # VFV
    {
        "device_type_id": 2,
        "sub_device_type_id": 11,
        "function": "Room Temp. (Get Temp. Status)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 11,
        "function": "Set Temp ( Get set temp. from thermostat)",
        "object_instance": "",
        "object_type": "Analogue Input",
        "range": "Deg C",
        "read_write": "Read",
    },
    {
        "device_type_id": 2,
        "sub_device_type_id": 11,
        "function": "Set Point ( Set Temp. on AC)",
        "object_instance": "",
        "object_type": "Analogue Output",
        "range": "Deg C",
        "read_write": "Write",
    },
]
